# Permalinks
permalink: :title

# Setup
author: Awn Umar
title: spacetime.dev
url: https://spacetime.dev
baseurl: ""

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# Markup
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

include: [_headers, _redirects]