# Permalinks
permalink: :title

# Setup
author: Awn Umar
title: spacetime.dev
url: https://ipfs.spacetime.dev
baseurl: ""

# Markup
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-katex

include: [_headers, _redirects]
